### ISSUE TITLE
Wrong output of one command in lecture 11

### ISSUE THREAD

**Issue by mistrjirka** [aicenter/FUP#28]
![obrazek](https://github.com/aicenter/FUP/assets/32205472/4ba5f92e-3cba-4446-a8fa-cbd2afa89a71)
Here the second command `parse ((/=) <$> item <*> item) "aac"` should output False
![Snímek obrazovky pořízený 2024-05-13 17-39-17](https://github.com/aicenter/FUP/assets/32205472/c1b938ee-f211-4648-9595-b92f4172f35a)

**Comment by nmheim** [comment]
Cool, great catch, thanks a lot @mistrjirka ! Addressed in #29
